### ISSUE TITLE
no such files ,how to do it

### ISSUE THREAD

**Issue by zhouqiw** [cody2007/alpha_go_zero_implementation#1]
./build.sh
...............................
includes.h:2:10: fatal error: arrayobject.h: No such file or directory
 #include "arrayobject.h

**Comment by cody2007** [comment]
Do you have python numpy installed? If not, install it and see if the problem is resolved.
If you do have it installed, find out where arrayobject.h is located on your computer and then make sure your compiler knows where to find it. On my machine (ubuntu 18.04), it is found here:
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h

Let me know if you need additional help.

**Comment by cody2007** [comment]
Unrelated to the problem you have here, but please make sure to pull the latest code. I just now made a minor change that fixes the policy target for training--it wasn't entirely correct before.
